### PR TITLE
interface for uploading package

### PR DESCRIPTION
**Pull request by TeKraft**
upload metadata as directive

### CODE REVIEW

**Review by Sijoma — APPROVED** [review]
Looks good. Do you present this at todays meeting? We should merge it afterwards. :+1:

**Comment by TeKraft** [comment]
Please do not merge. Needs some update

**Comment by TeKraft** [comment]
can be merged now

**Comment by jansule** [comment]
This still does not work for me. The metadata for a figure will not be stored in the DB. 
Steps to reproduce the problem:
1. upload ERC
2. in `required` tab add all required metadata
3. click `save`
4. go to `uibindings`
5. edit figure metadata
6. click `update`
7. check DB (`interaction is empty array)

**Note**: Lasse checked this as well and it didn't work neither.
*tested with firefox, chrome and chromium*

**Comment by TeKraft** [comment]
Do you also fill in the "widget" meta data or only the input fields for "figure" metadata?

**Comment by TeKraft** [comment]
I tested it again and it is possible to save.
workflow:

1. upload ERC

2. in required tab add all required metadata

3. click save

4. go to uibindings

5. edit figure metadata

6. edit widget metadata

7. click "add figure to UI bindings"

8. click update

9. check DB (`interaction has saved metadata)

**Pull request merged**
